package com.tahfizhonline.fungsidukung;

import java.util.ArrayList;
import java.util.List;

public class InfoDukung {

    public String namaSuroh(int noSuroh) {
        String[] daftarSurohAlQuran = new String[115];
        daftarSurohAlQuran[0] = "";
        daftarSurohAlQuran[2] = "Surat Al-Baqarah";
        daftarSurohAlQuran[1] = "Al-Fatihah";
        daftarSurohAlQuran[3] = "Al-i'Imran";
        daftarSurohAlQuran[4] = "An-Nisaa";
        daftarSurohAlQuran[5] = "Al-Maidah";
        daftarSurohAlQuran[6] = "Al-An'am";
        daftarSurohAlQuran[7] = "Al-A'raf";
        daftarSurohAlQuran[8] = "Al-Anfal";
        daftarSurohAlQuran[9] = "At-Tauba";
        daftarSurohAlQuran[10] = "Yunus";
        daftarSurohAlQuran[11] = "Hud";
        daftarSurohAlQuran[12] = "Yusuf";
        daftarSurohAlQuran[13] = "Ar-Ra'd";
        daftarSurohAlQuran[14] = "Ibrahim";
        daftarSurohAlQuran[15] = "Al-Hijr";
        daftarSurohAlQuran[16] = "An-Nahl";
        daftarSurohAlQuran[17] = "Al-Isra";
        daftarSurohAlQuran[18] = "Al-Kahfi";
        daftarSurohAlQuran[19] = "Maryam";
        daftarSurohAlQuran[20] = "Ta-ha";
        daftarSurohAlQuran[21] = "Al-Anbiyaa";
        daftarSurohAlQuran[22] = "Al-Hajj";
        daftarSurohAlQuran[23] = "Al-Muminun";
        daftarSurohAlQuran[24] = "An-Nur";
        daftarSurohAlQuran[25] = "Al-Furqan";
        daftarSurohAlQuran[26] = "Ash-Shu'araa";
        daftarSurohAlQuran[27] = "An-Naml";
        daftarSurohAlQuran[28] = "Al-Qashash";
        daftarSurohAlQuran[29] = "Al-Ankabut";
        daftarSurohAlQuran[30] = "Ar-Rum";
        daftarSurohAlQuran[31] = "Luqman";
        daftarSurohAlQuran[32] = "As-Sajdah";
        daftarSurohAlQuran[33] = "Al-Ahzab";
        daftarSurohAlQuran[34] = "Saba";
        daftarSurohAlQuran[35] = "Faathir";
        daftarSurohAlQuran[36] = "Ya-Sin";
        daftarSurohAlQuran[37] = "Ash-Shaffat";
        daftarSurohAlQuran[38] = "Sad";
        daftarSurohAlQuran[39] = "Az-Zumar";
        daftarSurohAlQuran[40] = "Al-Mu'min";
        daftarSurohAlQuran[41] = "Ha-Mim";
        daftarSurohAlQuran[42] = "Ash-Shura";
        daftarSurohAlQuran[43] = "Az-Zukhruf";
        daftarSurohAlQuran[44] = "Ad-Dukhan";
        daftarSurohAlQuran[45] = "Al-Jathiya";
        daftarSurohAlQuran[46] = "Al-Ahqaf";
        daftarSurohAlQuran[47] = "Muhammad";
        daftarSurohAlQuran[48] = "Al-Fat-h";
        daftarSurohAlQuran[49] = "Al-Hujurat";
        daftarSurohAlQuran[50] = "Qaaf";
        daftarSurohAlQuran[51] = "Az-Zariyat";
        daftarSurohAlQuran[52] = "At-Tur";
        daftarSurohAlQuran[53] = "An-Najm";
        daftarSurohAlQuran[54] = "Al-Qamar";
        daftarSurohAlQuran[55] = "Ar-Rahman";
        daftarSurohAlQuran[56] = "Al-Waaqi'ah";
        daftarSurohAlQuran[57] = "Al-Hadid";
        daftarSurohAlQuran[58] = "Al-Mujadila";
        daftarSurohAlQuran[59] = "Al-Hasyr";
        daftarSurohAlQuran[60] = "Al-Mumtahana";
        daftarSurohAlQuran[61] = "As-Shaff";
        daftarSurohAlQuran[62] = "Al-Jumu'ah";
        daftarSurohAlQuran[63] = "Al-Munafik";
        daftarSurohAlQuran[64] = "At-Tagabun";
        daftarSurohAlQuran[65] = "At-Talaq";
        daftarSurohAlQuran[66] = "At-Tahrim";
        daftarSurohAlQuran[67] = "Al-Mulk";
        daftarSurohAlQuran[68] = "Al-Qalam";
        daftarSurohAlQuran[69] = "Al-Haqqa";
        daftarSurohAlQuran[70] = "Al-Ma'arij";
        daftarSurohAlQuran[71] = "Nuh";
        daftarSurohAlQuran[72] = "Al-Jinn";
        daftarSurohAlQuran[73] = "Al-Muzzammil";
        daftarSurohAlQuran[74] = "Al-Muddathth";
        daftarSurohAlQuran[75] = "Al-Qiyamat";
        daftarSurohAlQuran[76] = "Ad-Dahr";
        daftarSurohAlQuran[77] = "Al-Mursalat";
        daftarSurohAlQuran[78] = "An-Nabaa";
        daftarSurohAlQuran[79] = "An-Nazi'at";
        daftarSurohAlQuran[80] = "Abasa";
        daftarSurohAlQuran[81] = "At-Takwir";
        daftarSurohAlQuran[82] = "Al-Infitar";
        daftarSurohAlQuran[83] = "Al-Mutaffif";
        daftarSurohAlQuran[84] = "Al-Inshiqaq";
        daftarSurohAlQuran[85] = "Al-Buruj";
        daftarSurohAlQuran[86] = "At-Tariq";
        daftarSurohAlQuran[87] = "Al-A'la";
        daftarSurohAlQuran[88] = "Al-Gashiya";
        daftarSurohAlQuran[89] = "Al-Fajr";
        daftarSurohAlQuran[90] = "Al-Balad";
        daftarSurohAlQuran[91] = "Ash-Shams";
        daftarSurohAlQuran[92] = "Al-Lail";
        daftarSurohAlQuran[93] = "Adz-Dhuha";
        daftarSurohAlQuran[94] = "Al-Syarh";
        daftarSurohAlQuran[95] = "At-Tin";
        daftarSurohAlQuran[96] = "Al-Alaq";
        daftarSurohAlQuran[97] = "Al-Qadr";
        daftarSurohAlQuran[98] = "Al-Baiyina";
        daftarSurohAlQuran[99] = "Al-Zalzalah";
        daftarSurohAlQuran[100] = "Al-Adiyat";
        daftarSurohAlQuran[101] = "Al-Qari'a";
        daftarSurohAlQuran[102] = "At-Takathur";
        daftarSurohAlQuran[103] = "Al-Asr";
        daftarSurohAlQuran[104] = "Al-Humaza";
        daftarSurohAlQuran[105] = "Al-Fil";
        daftarSurohAlQuran[106] = "Quraish";
        daftarSurohAlQuran[107] = "Al-Ma'un";
        daftarSurohAlQuran[108] = "Al-Kautsar";
        daftarSurohAlQuran[109] = "Al-Kaafirun";
        daftarSurohAlQuran[110] = "An-Nashr";
        daftarSurohAlQuran[111] = "Al-Lahab";
        daftarSurohAlQuran[112] = "Al-Ikhlas";
        daftarSurohAlQuran[113] = "Al-Falaq";
        daftarSurohAlQuran[114] = "An-Nas";

        return daftarSurohAlQuran[noSuroh];

    }
}
